apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp-deploy
  namespace: dev
  labels:
    app: bankapp-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bankapp-app
  template:
    metadata:
      labels:
        app: bankapp-app
    spec:
      containers:
      - name: bankapp-container
        image: raja012/bankapp-app
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: bankapp-np-service
  labels:
    app: bankapp-app
spec:
  selector:
    app: bankapp-app

  type: NodePort
  ports:
  - nodePort: 31030  
    port: 8081
    targetPort: 8081
